# Site settings
title: Luan Moises dos Santos Valadares
description: Aluno de licenciatura em  Matemática 
keywords: professor, , R, matemática
author: IMG_FSB
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:collection/:path/
