# Site settings
title:Erlane Santiago
description: Aluna de licenciatura em  Matemática 
keywords: professor, , R, matemática
author: Erlane
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:collection/:path/
